include:
  - project: solutions/pipeline-recipes
    file:
      - build-image.yaml
      - build-chart.yaml
      - lint-chart.yaml

stages:
  - test
  - deliver
  - qa

variables:
  CHART_DIR: chart/yubihsm-prometheus-exporter

