{{- if .Values.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "yubihsm-prometheus-exporter.fullname" . }}
  labels:
    {{- include "yubihsm-prometheus-exporter.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "yubihsm-prometheus-exporter.selectorLabels" . | nindent 6 }}    
  endpoints:
  - port: http
{{- end -}}
