apiVersion: vault.finleap.cloud/v1alpha1
kind: VaultSecret
metadata:
  name: {{ include "yubihsm-prometheus-exporter.fullname" . }}
  labels:
    {{- include "yubihsm-prometheus-exporter.labels" . | nindent 4 }}
spec:
  secretName: {{ include "yubihsm-prometheus-exporter.fullname" . }}
  data:
    {{- range $key, $definition := .Values.authentication_keys }}
    - name: {{ $key }}
      location:
        {{- with $definition.pin_vault }}
        path:    {{ .path }}
        field:   {{ .field }}
        {{- if .version }}
        version: {{ .version }}
        {{- end }}
        {{- end }}
    {{- end }}
